package com.daniel.bluetoothmic;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.media.*;import android.view.*;import android.widget.*;
public class MainActivity extends Activity{AudioRecord recorder;AudioTrack player;Thread thread;boolean running=false;TextView status;Button mic;int rate=44100;
public void onCreate(Bundle b){super.onCreate(b);ui();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},10);}
TextView tx(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setGravity(17);v.setPadding(12,12,12,12);return v;}
void ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(28,30,28,20);r.setBackgroundColor(Color.rgb(7,0,20));TextView title=tx("BLUETOOTH MIC",28);title.setTextColor(Color.CYAN);r.addView(title,new LinearLayout.LayoutParams(-1,80));status=tx("● READY TO CONNECT",16);status.setTextColor(Color.CYAN);r.addView(status,new LinearLayout.LayoutParams(-1,65));mic=new Button(this);mic.setText("🎙 START MICROPHONE");mic.setTextSize(18);r.addView(mic,new LinearLayout.LayoutParams(-1,125));TextView vl=tx("OUTPUT VOLUME",14);r.addView(vl);SeekBar vol=new SeekBar(this);vol.setMax(100);vol.setProgress(85);r.addView(vol,new LinearLayout.LayoutParams(-1,65));Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Voice: Normal","Voice: Echo","Voice: Robot","Voice: Deep","Voice: Monster"}));r.addView(sp,new LinearLayout.LayoutParams(-1,65));Button bt=new Button(this);bt.setText("⚡ OPEN BLUETOOTH SETTINGS");r.addView(bt,new LinearLayout.LayoutParams(-1,85));Button ab=new Button(this);ab.setText("ⓘ ABOUT");r.addView(ab,new LinearLayout.LayoutParams(-1,75));mic.setOnClickListener(v->{if(running)stopMic();else startMic();});bt.setOnClickListener(v->startActivity(new Intent(android.provider.Settings.ACTION_BLUETOOTH_SETTINGS)));ab.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Bluetooth Mic").setMessage("2027 Neon Bluetooth Microphone\n\nDeveloper: דניאל כרייף\ndani0534346135@gmail.com").setPositiveButton("OK",null).show());setContentView(r);}
void startMic(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},10);return;}int min=AudioRecord.getMinBufferSize(rate,16,2);int out=AudioTrack.getMinBufferSize(rate,4,2);recorder=new AudioRecord(1,rate,16,2,min);player=new AudioTrack(3,rate,4,2,out,1);recorder.startRecording();player.play();running=true;mic.setText("⏹ STOP MICROPHONE");status.setText("● LIVE — SPEAK NOW");thread=new Thread(()->{short[] b=new short[min];while(running){int n=recorder.read(b,0,b.length);if(n>0)player.write(b,0,n);}});thread.start();}
void stopMic(){running=false;try{recorder.stop();recorder.release();player.stop();player.release();}catch(Exception e){}mic.setText("🎙 START MICROPHONE");status.setText("● READY TO CONNECT");}
protected void onDestroy(){if(running)stopMic();super.onDestroy();}}
