plugins { id 'com.android.application' }

android {
    namespace 'com.daniel.bluetoothmic'
    compileSdk 35

    defaultConfig {
        applicationId 'com.daniel.bluetoothmic.android11'
        minSdk 26
        targetSdk 30
        versionCode 1
        versionName '2.1'
    }

    buildTypes {
        debug {
            debuggable true
        }
    }
}
